package spotifycharts;

import java.util.Random;

/**
 * a helper class for generating semi-random Song instances.
 */
public class SongBuilder {

    private static Random randomizer = new Random();
    private static int baseTitleNr = 0;

    public static void reSeed(long seed) {
        // fix the random generator to be able to reproduce results across different runs.
        randomizer = new Random(seed);
        baseTitleNr = randomizer.nextInt(titles.length);
    }

    /**
     * Creates a new Song instance with semi-random content from few popular song titles
     * @param titleNr   a sequence number that is used to assure uniqueness of all created songs.
     * @return
     */
    public static Song createSample(int titleNr) {
        // pick a semi-random title based on the provided title number.
        String titleText = titles[(baseTitleNr + 31 * titleNr) % titles.length];

        // extract Song attributes from the title text
        String[] titleParts = titleText.split("\\{");
        Song.Language language = titleParts.length > 1 ? Song.Language.valueOf(titleParts[1].substring(0,2).toUpperCase()) : Song.Language.EN;
        titleParts = titleParts[0].split("-");
        String artist = titleParts[0].trim();
        String title = titleParts[1].trim();

        // calculate a semi-random remix number to assure uniqueness of all titles
        int remixNr = titleNr / titles.length;
        if (remixNr > 0) {
            title = title + " (remix-" + remixNr + ")";
        }

        // build the Song from all info
        Song song = new Song(artist, title, language);

        return song;
    }

    private static String[] titles = {
            "$hirak - Als Je Bij Me Blijft {nl}",
            "ACRAZE - Do It To It",
            "Adele - Easy On Me",
            "Alessio - 1 Blik {nl}",
            "Alesso - Words",
            "Alok - All By Myself",
            "Alok - Deep Down",
            "Alvaro Soler - Solo Para Ti {sp}",
            "Antoon - Centraal Station {nl}",
            "Antoon - Hallo {nl}",
            "Antoon - Hotelschool {nl}",
            "Antoon - Klop Klop {nl}",
            "Antoon - Leuk {nl}",
            "Antoon - Meteoriet {nl}",
            "Antoon - Olivia {nl}",
            "Arctic Monkeys - 505",
            "Arctic Monkeys - Do I Wanna Know?",
            "Arctic Monkeys - I Wanna Be Yours",
            "Arctic Monkeys - Why'd You Only Call Me When You're High?",
            "Armani White - BILLIE EILISH.",
            "Avicii - Wake Me Up",
            "Bad Bunny - Efecto {sp}",
            "Bad Bunny - La Corriente {sp}",
            "Bad Bunny - Me Porto Bonito {sp}",
            "Bad Bunny - Moscow Mule",
            "Bad Bunny - Neverita {sp}",
            "Bad Bunny - Ojitos Lindos {sp}",
            "Bad Bunny - Party {sp}",
            "Bad Bunny - Tarot {sp}",
            "Bad Bunny - Tití Me Preguntó {sp}",
            "Bad Bunny - Un Coco {sp}",
            "Bad Bunny - Yonaguni {sp}",
            "Beach Weather - Sex, Drugs, Etc.",
            "Becky G - MAMIII",
            "Becky Hill & David Guetta - Remember ",
            "Benson Boone - In The Stars",
            "Bente - Als Geen Ander {nl}",
            "Beyoncé - CUFF IT",
            "Billie Eilish - Happier Than Ever",
            "Billie Eilish - lovely",
            "Billie Eilish - TV",
            "Bizarrap - Quevedo: Bzrp Music Sessions, Vol. 52",
            "BLACKPINK - Pink Venom",
            "BLACKPINK - Shut Down",
            "Boef - Flexxen {nl}",
            "Broederliefde - Déjà Vu",
            "Broederliefde - Laten Landen {nl}",
            "Bruno Mars - Locked Out Of Heaven",
            "Bruno Mars - When I Was Your Man",
            "Burna Boy - For My Hand",
            "Burna Boy - Last Last",
            "Calvin Harris - One Kiss",
            "Camila Cabello - Bam Bam",
            "Central Cee - Doja",
            "Charlie Puth - Left and Right (Feat. Jung Kook of BTS)",
            "Chris Brown - Under The Influence",
            "Cigarettes After Sex - Apocalypse",
            "Coldplay - My Universe",
            "Coldplay - Viva La Vida",
            "Coldplay - Yellow",
            "Conan Gray - Heather",
            "Connor Price - Spinnin",
            "Coolio - Gangsta's Paradise",
            "Cris Mj - Una Noche en Medellín {sp}",
            "Cults - Gilded Lily",
            "d4vd - Here With Me",
            "d4vd - Romantic Homicide",
            "Danny Vera - Roller Coaster",
            "David Guetta - Crazy What Love Can Do",
            "David Guetta - I'm Good (Blue)",
            "Davina Michelle - I Love Me More",
            "De Jeugd Van Tegenwoordig - Sterrenstof {nl}",
            "Dean Lewis - Be Alright",
            "Dean Lewis - How Do I Say Goodbye",
            "DI-RECT - 90s Kid",
            "DI-RECT - Through The Looking Glass",
            "Dimitri Vegas - The Drop",
            "Djaga Djaga - ABC",
            "Doja Cat - Vegas (From the Original Motion Picture Soundtrack ELVIS)",
            "Doja Cat - Woman",
            "Donnie - Bon Gepakt {nl}",
            "Drake - Jimmy Cooks",
            "Dua Lipa - Levitating",
            "Duncan Laurence - Electric Life",
            "Ed Sheeran - Bad Habits",
            "Ed Sheeran - Celestial",
            "Ed Sheeran - Perfect",
            "Ed Sheeran - Shivers",
            "Eliza Rose - B.O.T.A. (Baddest Of Them All)",
            "Elley Duhé - MIDDLE OF THE NIGHT",
            "Elton John - Cold Heart",
            "Elton John - Hold Me Closer",
            "Elton John - I'm Still Standing",
            "Eminem - 'Till I Collapse",
            "Eminem - Lose Yourself",
            "Eminem - Mockingbird",
            "Eminem - Superman",
            "Eminem - The Real Slim Shady",
            "Eminem - Without Me",
            "Farruko - Pepas",
            "Feid - Feliz Cumpleaños Ferxxo {sp}",
            "Feid - Normal {sp}",
            "FLEMMING - Amsterdam {nl}",
            "FLEMMING - Automatisch {nl}",
            "FLEMMING - Terug Bij Af {nl}",
            "Flemming - Zij Wil Mij {nl}",
            "Fmg - Boot {nl}",
            "Froukje - Niets Tussen {nl}",
            "Future - WAIT FOR U",
            "Gabry Ponte - Thunder",
            "Gabry Ponte - We Could Be Together",
            "George Ezra - Green Green Grass",
            "Ghost - Mary On A Cross",
            "girl in red - we fell in love in october",
            "Glass Animals - Heat Waves",
            "GLOWINTHEDARK - Dansen Op Labanta {nl}",
            "Goldband - Noodgeval {nl}",
            "Goldband - Witte Was {nl}",
            "Grupo Frontera - No Se Va - En Vivo {sp}",
            "Gustavo Mioto - Eu Gosto Assim (Ao Vivo) {sp}",
            "Harry Styles - As It Was",
            "Harry Styles - Late Night Talking",
            "Harry Styles - Watermelon Sugar",
            "Hotel Ugly - Shut up My Moms Calling",
            "Idaly - Amazin'",
            "Imagine Dragons - Believer",
            "Imagine Dragons - Bones",
            "Imagine Dragons - Enemy",
            "Imanbek - Belly Dancer",
            "IVE - After LIKE",
            "J Balvin - LA CANCIÓN {sp}",
            "J. Cole - No Role Modelz",
            "Jaap Reesema - Alles Komt Goed {nl}",
            "Jaap Reesema - Grijs {nl}",
            "Jaap Reesema - Mijn Kleine Presidentje {nl}",
            "Jaap Reesema - Nu Wij Niet Meer Praten {nl}",
            "James Hype - Ferrari",
            "Jhayco - En La De Ella {sp}",
            "Jinho 9 - Blind Op Zoek (Trapagas) {nl}",
            "Jinho 9 - Interessant {nl}",
            "JoeyAK - Blijf Soldaat {nl}",
            "Joji - Glimpse of Us",
            "Josylvio - Soms",
            "Justin Bieber - Ghost",
            "JVKE - golden hour",
            "KA - Jongen Als Mij {nl}",
            "Kanye West - Bound 2",
            "KAROL G - GATÚBELA {sp}",
            "KAROL G - PROVENZA {sp}",
            "Kate Bush - Running Up That Hill (A Deal With God)",
            "KATNUF - Van Mij Zijn {nl}",
            "Keane - Somewhere Only We Know",
            "Keane - Somewhere Only We Know",
            "Kendrick Lamar - Money Trees",
            "Kenshi Yonezu - KICK BACK",
            "Kinderen voor Kinderen - Gi-ga-groen {nl}",
            "Kleine John - BALANCE {nl}",
            "Kordhell - Murder In My Mind",
            "Kris Kross Amsterdam - Adrenaline {nl}",
            "Kris Kross Amsterdam - Vanavond (Uit M'n Bol) {nl}",
            "Kris Kross Amsterdam - Vluchtstrook {nl}",
            "La Fuente - I Want You",
            "Lady Gaga - Shallow",
            "Lana Del Rey - Summertime Sadness",
            "LE SSERAFIM - ANTIFRAGILE",
            "Lewis Capaldi - Before You Go",
            "Lewis Capaldi - Forget Me",
            "Lewis Capaldi - Someone You Loved",
            "LF SYSTEM - Afraid To Feel",
            "Lijpe - El Clásico {nl}",
            "Lil Nas X - INDUSTRY BABY",
            "Lil Nas X - STAR WALKIN' (League of Legends Worlds Anthem)",
            "Lil Uzi Vert - Just Wanna Rock",
            "Lil Yachty - Poland",
            "Lizzo - 2 Be Loved (Am I Ready)",
            "Lizzo - About Damn Time",
            "Lost Frequencies - Questions",
            "Lost Frequencies - Where Are You Now",
            "Luar La L - Caile {sp}",
            "Maan - Naar De Maan {nl}",
            "Maan - Sowieso Overhoop {nl}",
            "Machario - Peace Of Mind",
            "Macklemore & Ryan Lewis - Can't Hold Us",
            "Makar - Mood",
            "Måneskin - THE LONELIEST",
            "Manuel Turizo - La Bachata {sp}",
            "Maroon 5 - Payphone",
            "Marshmello - Bye Bye",
            "Marshmello - Numb",
            "Mart Hoogkamer - Bieber Van De Kroeg {nl}",
            "Mau P - Drugs From Amsterdam",
            "MEAU - Blijven Rijden {nl}",
            "MEAU - Dans M'n Ogen Dicht {nl}",
            "MEAU - Dat heb jij gedaan {nl}",
            "MEDUZA - Bad Memories",
            "Meghan Trainor - Made You Look",
            "Mora - LA INOCENTE {sp}",
            "Mr.Kitty - After Dark",
            "Nathan Dawe - 21 Reasons",
            "Natte Visstick - Visstick Gooi Die Kanker Kick {nl}",
            "NewJeans - Hype Boy",
            "Nicki Minaj - Super Freaky Girl",
            "Nicky Youre - Sunroof",
            "Nirvana - Smells Like Teen Spirit",
            "Oliver Tree - Miss You",
            "Olivia Rodrigo - deja vu",
            "Olivia Rodrigo - drivers license",
            "Olivia Rodrigo - good 4 u",
            "Olivia Rodrigo - traitor",
            "Omar Apollo - Evergreen",
            "One Direction - Night Changes",
            "OneRepublic - Counting Stars",
            "OneRepublic - I Ain't Worried",
            "OneRepublic - Sunshine",
            "OsTEKKe - Another Love",
            "Oxlade - KU LO SA, A COLORS SHOW",
            "Ozuna - Hey Mor",
            "Pablito Pesadilla - BABY OTAKU {sp}",
            "Paloma Faith - Only Love Can Hurt Like This",
            "Passenger - Let Her Go",
            "Patrick Watson - Je te laisserai des mots {fr}",
            "Peso Pluma - Siempre Pendientes {sp}",
            "Post Malone - I Like You (A Happier Song)",
            "Post Malone - Sunflower, Spider-Man: Into the Spider-Verse",
            "Quevedo - Vista Al Mar {sp}",
            "Racoon - Oceaan {nl}",
            "Rauw Alejandro - Desesperados {sp}",
            "Rauw Alejandro - LOKERA {sp}",
            "Rauw Alejandro - PUNTO 40 {sp}",
            "Rels B - cómo dormiste? {sp}",
            "Rema - Calm Down",
            "RONDÉ - Bright Eyes",
            "RONDÉ - Love Myself",
            "Rosa Linn - SNAP",
            "ROSALÍA - DESPECHÁ {sp}",
            "Ruth B. - Dandelions",
            "S10 - De Diepte {nl}",
            "Sam Smith - I'm Not The Only One",
            "Sam Smith - Unholy",
            "Seafret - Atlantis",
            "Sevn Alias - Train",
            "Shakira - Monotonía {sp}",
            "Shakira - Te Felicito {sp}",
            "Sia - Unstoppable",
            "Siggy & D1ns - All Eyes On Me",
            "Sigourney K - 100 SMSjes {nl}",
            "Snelle - Blijven Slapen {nl}",
            "Snelle - In M'n Bloed {nl}",
            "Snelle - Pizza Met Ananas {nl}",
            "Son Mieux - Multicolor",
            "southstar - Miss You",
            "Stephen Sanchez - Until I Found You",
            "Steve Lacy - Bad Habit",
            "Steve Lacy - Dark Red",
            "Steve Lacy - Static",
            "Stevy - Criminal",
            "Stormzy - Hide & Seek",
            "Suzan & Freek - Goud {nl}",
            "Suzan & Freek - Honderd Keer {nl}",
            "Suzan & Freek - Kwijt {nl}",
            "Taylor Swift - Anti-Hero",
            "Taylor Swift - august",
            "Taylor Swift - Bejeweled",
            "Taylor Swift - Bigger Than The Whole Sky",
            "Taylor Swift - Blank Space",
            "Taylor Swift - Dear Reader",
            "Taylor Swift - Don’t Blame Me",
            "Taylor Swift - Glitch",
            "Taylor Swift - High Infidelity",
            "Taylor Swift - Karma",
            "Taylor Swift - Labyrinth",
            "Taylor Swift - Lavender Haze",
            "Taylor Swift - Maroon",
            "Taylor Swift - Mastermind",
            "Taylor Swift - Midnight Rain",
            "Taylor Swift - Paris",
            "Taylor Swift - Question...?",
            "Taylor Swift - Snow On The Beach",
            "Taylor Swift - Sweet Nothing",
            "Taylor Swift - The Great War",
            "Taylor Swift - Vigilante Shit",
            "Taylor Swift - Would've, Could've, Should've",
            "Taylor Swift - You're On Your Own, Kid",
            "The Game - Hate It Or Love It",
            "The Kid LAROI - Stay",
            "The Neighbourhood - Daddy Issues",
            "The Neighbourhood - Sweater Weather",
            "The Police - Every Breath You Take",
            "The Walters - I Love You So",
            "The Weeknd - Blinding Lights",
            "The Weeknd - Call Out My Name",
            "The Weeknd - Die For You",
            "The Weeknd - I Was Never There",
            "The Weeknd - Save Your Tears",
            "The Weeknd - Starboy",
            "The Weeknd - Stargirl Interlude",
            "The Weeknd - The Hills",
            "Tiësto - Hot In It",
            "Tiësto - The Motto",
            "Tom Odell - Another Love",
            "Topic - Kernkraft 400 (A Better Day)",
            "TOTO - Africa",
            "Vance Joy - Riptide",
            "Willem & Jan - Tussen Jou en Mij {nl}",
            "Wisin & Yandel - Besos Moja2 {sp}",
            "XXXTENTACION - Revenge",
            "Yade Lauren - In De Nacht {nl}",
            "Yade Lauren - Swim Deep {nl}",
            "Yade Lauren - Toxic {nl}",
            "Zach Bryan - Something in the Orange",
            "Zoë Tauran - Gebruik Me {nl}",
            "Zoë Tauran - Solo {nl}"
    };
}
